spring:
  application:
    name: online-pizza-service
  datasource:
    url: jdbc:h2:mem:universityDB
    username: admin
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080